services:
  marzneshin:
    image: dawsh/marzneshin:latest
    restart: always
    env_file: .env
    network_mode: host
    environment:
      SQLALCHEMY_DATABASE_URL: "sqlite:////var/lib/marzneshin/db.sqlite3"
    volumes:
      - /var/lib/marzneshin:/var/lib/marzneshin
    ports:
      - "8000:8000"
    networks:
      - marzneshin-net

  marznode:
    image: dawsh/marznode:latest
    restart: always
    network_mode: host
    environment:
      SERVICE_ADDRESS: "127.0.0.1"
      INSECURE: "True"
      XRAY_EXECUTABLE_PATH: "/usr/local/bin/xray"
      XRAY_ASSETS_PATH: "/usr/local/lib/xray"
      XRAY_CONFIG_PATH: "/var/lib/marznode/xray_config.json"
      SSL_KEY_FILE: "./server.key"
      SSL_CERT_FILE: "./server.cert"
    volumes:
      - /var/lib/marznode:/var/lib/marznode

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - /opt/marzneshin/nginx.conf:/etc/nginx/nginx.conf
      - /var/lib/marzneshin/certs:/etc/nginx/certs
      - /var/www/html:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - marzneshin
    networks:
      - marzneshin-net
  wgcf-warp:
    image: linuxserver/wireguard
    container_name: wgcf-warp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - /opt/marzneshin/wgcf:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
    networks:
      - marzneshin-net

networks:
  marzneshin-net:
    driver: bridge
